# En este Notebook se van a concatenar los datos obtenidos en Notebooks anteriores con los del proyecto ETL mencionado en el README para obtener la serie completa.

In [23]:
import numpy as np
import pylab as plt   
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import sys
sys.path.append('../src')
from funflights import *

In [2]:
fl1 = pd.read_csv("../data/flights/flights2017_2019.csv", encoding = "latin1")
fl2 = pd.read_csv("../data/flights/flights2020_2022.csv", encoding = "latin1")
fl3 = pd.read_csv("../data/flights/flights.csv", encoding = "latin1")

In [3]:
fl1.shape

(439088, 22)

In [4]:
fl2.shape

(306924, 22)

In [5]:
fl3.shape

(176596, 22)

In [6]:
fl = pd.concat([fl1,fl2,fl3])

In [7]:
fl.shape

(922608, 22)

In [16]:
fl.head()

,flight_id,departure_date_time,cod_flight_IATA,cod_flight_ICAO,day,week_day,status,airliner,cod_airliner_IATA,cod_airliner_ICAO,...,dep_situation,dep_mins_of_delay,city,cod_airport_IATA,cod_airport_ICAO,arrival,arr_situation,arr_mins_of_delay,duration,resta
0,3,2023-10-31 23:59:00,IB6833,IBE6833,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,...,late,35,Santiago,SCL,SCEL,09:13 UTC-03,early,-6,13h,41
1,1,2023-10-31 23:59:00,IB6841,IBE6841,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,...,late,33,Buenos Aires,EZE,SAEZ,08:29 UTC-03,on time,0,12h,33
2,2,2023-10-31 23:59:00,IB6011,IBE6011,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,...,late,25,Montevideo,MVD,SUMU,08:48 UTC-03,early,-6,12h,31
3,5,2023-10-31 23:55:00,IB6589,IBE6589,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,...,late,24,Bogota,BOG,SKBO,03:52 UTC-05,early,-27,10h,51
4,8,2023-10-31 23:55:00,IB6409,IBE6409,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,...,late,48,Mexico City,MEX,MMMX,04:55 CST,early,-19,11h,67

In [18]:
columnas_excepto_una = fl.columns.difference(['flight_id'])  
fl = fl.drop_duplicates(subset=columnas_excepto_una, keep='first')
fl.shape

(922599, 22)

In [21]:
fl['flight_id'] = range(1, len(fl) + 1)
fl = fl.reset_index(drop = True)
fl.tail()

,flight_id,departure_date_time,cod_flight_IATA,cod_flight_ICAO,day,week_day,status,airliner,cod_airliner_IATA,cod_airliner_ICAO,...,dep_situation,dep_mins_of_delay,city,cod_airport_IATA,cod_airport_ICAO,arrival,arr_situation,arr_mins_of_delay,duration,resta
922594,922595,2017-11-01 00:40:00,IB6841,IBE6841,2017-11-01,Wednesday,Landed,Iberia,IB,IBE,...,late,13,Buenos Aires,EZE,SAEZ,08:47 UTC-03,early,-37,12h,50
922595,922596,2017-11-01 00:40:00,IB6409,IBE6409,2017-11-01,Wednesday,Landed,Iberia,IB,IBE,...,late,31,Mexico City,MEX,MMMX,05:33 CST,early,-16,11h,47
922596,922597,2017-11-01 00:13:00,FX5036,FDX5036,2017-11-01,Wednesday,Landed,Federal Express (FedEx),FX,FDX,...,on time,0,Paris,CDG,LFPG,01:40 CET,on time,0,1h,0
922597,922598,2017-11-01 00:10:00,IB3118,IBE3118,2017-11-01,Wednesday,Landed,Iberia,IB,IBE,...,late,5,Lisbon,LIS,LPPT,00:09 WET,early,-15,53m,20
922598,922599,2017-11-01 00:05:00,TP1005,TAP1005,2017-11-01,Wednesday,Landed,TAP - Air Portugal,TP,TAP,...,late,7,Porto,OPO,LPPR,00:05 WET,early,-10,52m,17

In [3]:
pd.set_option('display.max_rows', None)

In [25]:
fl.cod_flight_ICAO[fl.cod_flight_ICAO.isna()] = "-"

In [35]:
pd.set_option('display.max_columns', None)
fl.head()

,flight_id,departure_date_time,cod_flight_IATA,cod_flight_ICAO,day,week_day,status,airliner,cod_airliner_IATA,cod_airliner_ICAO,Scheduled_dep,depart_time,dep_situation,dep_mins_of_delay,city,cod_airport_IATA,cod_airport_ICAO,arrival,arr_situation,arr_mins_of_delay,duration,resta
0,1,2023-10-31 23:59:00,IB6833,IBE6833,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,23:59,00:34,late,35,Santiago,SCL,SCEL,09:13 UTC-03,early,-6,13h,41
1,2,2023-10-31 23:59:00,IB6841,IBE6841,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,23:59,00:32,late,33,Buenos Aires,EZE,SAEZ,08:29 UTC-03,on time,0,12h,33
2,3,2023-10-31 23:59:00,IB6011,IBE6011,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,23:59,00:24,late,25,Montevideo,MVD,SUMU,08:48 UTC-03,early,-6,12h,31
3,4,2023-10-31 23:55:00,IB6589,IBE6589,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,23:55,00:19,late,24,Bogota,BOG,SKBO,03:52 UTC-05,early,-27,10h,51
4,5,2023-10-31 23:55:00,IB6409,IBE6409,2023-10-31,Tuesday,Landed,Iberia,IB,IBE,23:55,00:43,late,48,Mexico City,MEX,MMMX,04:55 CST,early,-19,11h,67

In [32]:
fl.to_csv("../data/flights/flights_total.csv", index=False)