In [1]:
import sys
import time
sys.path.append('../src')
from funpipes import *

In [2]:
%%time
fl = procesar_datos(scrape_flightera_data(), scrape_tutiempo_data())
fl.head()

Extraction completed
Aceptado normas
Aceptadas cookies
Página cargada
Registros extraídos
Aceptado normas
Aceptadas cookies
View last 24h
Página cargada
Registros extraídos
CPU times: total: 1 s
Wall time: 2min 49s

,status,cod_flight_IATA,week_day,week_num,cod_airliner_IATA,cod_airport_IATA,hour,duration,Condition,Temperature,Wind,day_time,acc_Gusts,acc_bad_weather
0,On Time,IB6653,Wednesday,49,IB,LIM,2023-12-05 00:20:00,12,Cloudy,6,7,Early Morning,0,0.0
1,Delayed,AV47,Wednesday,49,AV,BOG,2023-12-05 00:35:00,10,Cloudy,6,7,Early Morning,0,0.0
2,On Time,LA2485,Wednesday,49,LA,LIM,2023-12-05 00:55:00,12,Cloudy,6,7,Early Morning,0,0.0
3,On Time,EK9390,Wednesday,49,EK,DWC,2023-12-05 01:10:00,7,Rain,6,6,Early Morning,0,0.0
4,On Time,FR2015,Wednesday,49,FR,ACE,2023-12-05 05:45:00,3,Partly cloudy,5,4,Early Morning,0,0.0